"use client";

import { useLanguage } from "../../../components/LanguageProvider";
import Link from "next/link";

export default function AboutPage() {
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-white pb-32 font-sans text-slate-900">
      <section className="mx-auto max-w-4xl px-6 pt-24 pb-16 space-y-8">
        <div className="text-[11px] font-black tracking-widest text-sky-600 uppercase italic">Vision & Identity</div>
        <h1 className="text-5xl md:text-8xl font-black tracking-tighter uppercase leading-none italic">
          Pocket <span className="text-sky-600">Dive</span>
        </h1>
        <p className="max-w-xl text-lg md:text-xl font-bold leading-tight text-slate-500">
          {t("「科学を、もっと身近なものに」。そんな想いから、AIを駆使した探索プラットフォームは生まれました。", "Bringing science closer to everyone. A next-gen exploration platform powered by AI.")}
        </p>
      </section>

      <main className="mx-auto max-w-4xl px-6">
        <div className="border-t border-slate-100 pt-16 space-y-20">

          <section className="grid grid-cols-1 md:grid-cols-3 gap-12">
            <div className="text-[11px] font-black tracking-widest text-slate-300 uppercase">01 / Motivation</div>
            <div className="md:col-span-2 space-y-6 text-base md:text-lg font-bold leading-relaxed text-slate-700">
              <p>
                {t("最先端の科学の世界を知るには論文は欠かせません。しかし、専門用語の壁や、膨大な量の中から自分に合ったものを探すハードルは依然として高いままです。",
                  "Original research is the heartbeat of science. Yet, the wall of jargon and the sheer volume of papers make it inaccessible for many.")}
              </p>
              <p>
                {t("科学は一部の専門家だけのものではなく、好奇心を持つすべての人に開かれているべきだと信じています。私たちは、その「入り口」をポケットの中に作りました。",
                  "We believe science belongs to everyone with a curious mind. We built the gateway right in your pocket.")}
              </p>
            </div>
          </section>

          <section className="grid grid-cols-1 md:grid-cols-3 gap-12">
            <div className="text-[11px] font-black tracking-widest text-slate-300 uppercase">02 / Solution</div>
            <div className="md:col-span-2 space-y-6 text-base md:text-lg font-bold leading-relaxed text-slate-700">
              <p>
                {t("Pocket Diveは、AIが膨大な論文データベースから価値ある知見を抽出し、「一般」と「専門家」の二つの視点で要約を提供します。",
                  "Pocket Dive uses AI to distill vast research databases into dual-depth summaries, catering to both curious minds and experts.")}
              </p>
              <div className="p-10 rounded-2xl bg-sky-50 border border-sky-100 space-y-4">
                <p className="text-sky-700">
                  {t("中高生には「研究という選択肢」を。社会人には「科学的思考のアップデート」を。",
                    "Opening the path of research for students, and upgrading scientific literacy for everyone.")}
                </p>
                <div className="pt-4 border-t border-sky-100">
                  <p className="text-[10px] text-slate-400 font-medium italic">
                    {t("*本サービスのロゴデザインは、Genspark AIによって生成されたものです。利用規約に従い、AI生成物であることを明記しています。", "*The logo design for this service was generated by Genspark AI. In accordance with terms, it is clearly stated as AI-generated.")}
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="grid grid-cols-1 md:grid-cols-3 gap-12 pt-16 border-t border-slate-100">
            <div className="text-[11px] font-black tracking-widest text-slate-300 uppercase">03 / Identity</div>
            <div className="md:col-span-2 flex items-center gap-6">
              <div className="w-16 h-16 rounded-2xl bg-slate-900 flex items-center justify-center text-white font-black text-2xl italic shadow-xl">S</div>
              <div>
                <div className="text-xl font-black uppercase text-slate-900 leading-none">Saola</div>
                <div className="text-[11px] font-black tracking-widest text-slate-400 uppercase mt-2">Developer / High School Student</div>
              </div>
            </div>
          </section>

          <div className="flex justify-center pt-12">
            <Link href="/" className="px-12 py-4 bg-slate-900 text-white font-black text-[12px] tracking-widest uppercase rounded-lg hover:bg-sky-600 transition-all shadow-xl shadow-slate-900/10">
              {t("ホームへ戻る", "Back to Home")}
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
